name: Deploy Github Page

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm run build:prod
