name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.0.1]
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build:prod
